from jwcrypto import jwk, jwe
from jwcrypto.common import json_encode, json_decode
public_key = jwk.JWK()
private_key = jwk.JWK.generate(kty='RSA', size=2048)
public_key.import_key(**json_decode(private_key.export_public()))
print("-------public key-------")
print(private_key.export_public())

print("-------private key-------")
print(private_key.export())
print('copy dictionary in to html')
print('paste jwe result generated by web console')
webResult = input(":")
jwetoken = jwe.JWE()
jwetoken.deserialize(webResult, key=private_key)
payload = jwetoken.payload
print(payload)
